create table if not exists public.reports (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    category text not null check (category in ('safety', 'vehicle', 'passenger', 'station', 'other')),
    priority text not null default 'normal' check (priority in ('normal', 'high', 'critical')),
    description text not null check (char_length(trim(description)) between 5 and 2000),
    latitude double precision,
    longitude double precision,
    status text not null default 'open' check (status in ('open', 'in_progress', 'resolved')),
    created_at timestamptz not null default timezone('utc', now()),
    resolved_at timestamptz
);

create index if not exists reports_created_at_idx
    on public.reports (created_at desc);

create index if not exists reports_user_id_idx
    on public.reports (user_id);

alter table public.reports enable row level security;

drop policy if exists "Users can create their own reports" on public.reports;
create policy "Users can create their own reports"
    on public.reports for insert
    with check (auth.uid() = user_id);

drop policy if exists "Users can view their own reports" on public.reports;
create policy "Users can view their own reports"
    on public.reports for select
    using (auth.uid() = user_id);