create table if not exists public.volunteer_assignments (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    station_name text not null,
    station_address text,
    active boolean not null default true,
    assigned_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists one_active_assignment_per_user_idx
    on public.volunteer_assignments (user_id)
    where active = true;

alter table public.volunteer_assignments enable row level security;

drop policy if exists "Users can view their own assignment" on public.volunteer_assignments;
create policy "Users can view their own assignment"
    on public.volunteer_assignments for select
    using (auth.uid() = user_id);