create table if not exists public.volunteer_tasks (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null,
    assigned_to_email text not null,
    priority text not null default 'normal' check (priority in ('normal', 'high', 'critical')),
    due_date date,
    status text not null default 'pending' check (status in ('pending', 'in_progress', 'done')),
    created_by_email text,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists volunteer_tasks_assigned_email_idx
    on public.volunteer_tasks (assigned_to_email);

create index if not exists volunteer_tasks_status_idx
    on public.volunteer_tasks (status);

alter table public.volunteer_tasks enable row level security;

drop policy if exists "Admins can manage tasks" on public.volunteer_tasks;
create policy "Admins can manage tasks"
    on public.volunteer_tasks
    for all
    using (true)
    with check (true);

drop policy if exists "Users can view their own tasks" on public.volunteer_tasks;
create policy "Users can view their own tasks"
    on public.volunteer_tasks
    for select
    using (auth.uid() is not null and assigned_to_email = lower(auth.email()));
